use am039583_db;

CREATE TABLE WEEKEND
(ID                     INT(11) NOT NULL,
 START_DATE             DATE,
 END_DATE               DATE,
 LOCATION               VARCHAR(30),
 WEEKEND_GENDER         VARCHAR(1),
 PRIMARY KEY(ID));

CREATE TABLE CURSILLISTA
(ID                    INT(12) NOT NULL,
 FIRST_NAME            VARCHAR(30),
 MIDDLE_NAME           VARCHAR(30),
 LAST_NAME             VARCHAR(30),
 TAG_NAME              VARCHAR(30),
 SPONSOR_NAME          VARCHAR(30),
 SPOUSE_NAME           VARCHAR(30),
 PASTOR_NAME           VARCHAR(30), 
 AGE                   INT(3),
 DATE_OF_BIRTH         DATE,
 EMAIL                 VARCHAR(30),
 HOME_PHONE            INT(10),
 MOBILE_PHONE          INT(10),
 WORK_PHONE            INT(10),
 STREET                VARCHAR(30),
 CITY                  VARCHAR(30),
 STATE                 VARCHAR(30),
 ZIP                   VARCHAR(5),
 PARISH_LIST_ID        INT(8) NOT NULL DEFAULT 0,
 TYPE                  VARCHAR(30), 
 OCCUPATION            VARCHAR(30),
 PRIMARY KEY(ID));

CREATE TABLE PARISH_LIST
(ID                    INT(8) NOT NULL,
 NAME                  VARCHAR(30),
 LOCATION              VARCHAR(30),
 CITY                  VARCHAR(30),
 STATE                 VARCHAR(2),
 ZIP                   INT(5),
 PRIMARY KEY(ID));

CREATE TABLE POSITIONS
(ID                    INT(13) NOT NULL,
 SUPERVISOR_NAME       VARCHAR(30),
 DESCRIPTION           VARCHAR(64),
 AVAILABILITY          VARCHAR(1),
 PRIMARY KEY(ID));

CREATE TABLE CURSILLISTA_PAST_POSITION
(CURSILLISTA_ID        INT(12) NOT NULL,
 PAST_POSITION         VARCHAR(30));

CREATE TABLE CURSILLISTA_CURRENT_POSITION
(CURSILLISTA_ID        INT(12) NOT NULL,
 CURRENT_POSITION      VARCHAR(30));

CREATE TABLE CURSILLISTA_FUTURE_POSITION
(CURSILLISTA_ID        INT(12) NOT NULL,
 FUTURE_POSITION       VARCHAR(30));

CREATE TABLE TEAM
(ID                    INT(14) NOT NULL,
 ROLE                  VARCHAR(30),
 CURSILLISTA_ID        INT(12) NOT NULL,
 PRIMARY KEY(ID));

CREATE TABLE CURSILLISTA_TEAM
(CURSILLISTA_ID        INT(12) NOT NULL,
 TEAM_ID               INT(14) NOT NULL);

CREATE TABLE CANDIDATE
(CURSILLISTA_ID        INT(12) NOT NULL);

CREATE TABLE TALK
(ID                    INT(15) NOT NULL,
 AVAILABILITY          VARCHAR(1),
 DESCRIPTION           VARCHAR(64),
 WEEKEND_ID            INT(11) NOT NULL,
 PRIMARY KEY(ID));

CREATE TABLE POSITION_TALK
(POSITION_ID           INT(13) NOT NULL,
 TALK_ID               INT(15) NOT NULL,
 PRIMARY KEY (POSITION_ID, TALK_ID));
 
ALTER TABLE CURSILLISTA ADD CONSTRAINT FK_CU_PARISH_LIST_ID FOREIGN KEY (PARISH_LIST_ID) REFERENCES PARISH_LIST(ID);
ALTER TABLE CURSILLISTA_PAST_POSITION ADD CONSTRAINT FK_CPP_CURSILLISTA_ID FOREIGN KEY (CURSILLISTA_ID) REFERENCES CURSILLISTA(ID);
ALTER TABLE CURSILLISTA_CURRENT_POSITION ADD CONSTRAINT FK_CCP_CURSILLISTA_ID FOREIGN KEY (CURSILLISTA_ID) REFERENCES CURSILLISTA(ID);
ALTER TABLE CURSILLISTA_FUTURE_POSITION ADD CONSTRAINT FK_CFP_CURSILLISTA_ID FOREIGN KEY (CURSILLISTA_ID) REFERENCES CURSILLISTA(ID);
ALTER TABLE TEAM ADD CONSTRAINT FK_TE_CURSILLISTA_ID FOREIGN KEY (CURSILLISTA_ID) REFERENCES CURSILLISTA(ID);
ALTER TABLE CURSILLISTA_TEAM ADD CONSTRAINT FK_CT_CURSILLISTA_ID FOREIGN KEY (CURSILLISTA_ID) REFERENCES CURSILLISTA(ID);
ALTER TABLE CURSILLISTA_TEAM ADD CONSTRAINT FK_CT_TEAM_ID FOREIGN KEY (TEAM_ID) REFERENCES TEAM(ID);
ALTER TABLE CANDIDATE ADD CONSTRAINT FK_CA_CURSILLISTA_ID FOREIGN KEY (CURSILLISTA_ID) REFERENCES CURSILLISTA(ID);
ALTER TABLE TALK ADD CONSTRAINT FK_TA_WEEKEND_ID FOREIGN KEY (WEEKEND_ID) REFERENCES WEEKEND(ID);
ALTER TABLE POSITION_TALK ADD CONSTRAINT FK_PT_POSITION_ID FOREIGN KEY (POSITION_ID) REFERENCES POSITIONS(ID);
ALTER TABLE POSITION_TALK ADD CONSTRAINT FK_PT_TALK_ID FOREIGN KEY (TALK_ID) REFERENCES TALK(ID);

INSERT INTO WEEKEND VALUES(478752, '2016-11-05', '2016-11-09', 'ORLANDO', 'M');
INSERT INTO PARISH_LIST VALUES(32, 'SJBEF', 'SEKJFE', 'OFESIO', 'GA', 34986);
INSERT INTO POSITIONS VALUES(3224, 'SHS', 'SKDHGDS', 'N');

 COMMIT;